# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
<<<<<<< HEAD
- master
=======
- develop
>>>>>>> 8cb942a0e18424c856b6673bef1aad243163e33f

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
<<<<<<< HEAD
    export VUE_APP_API_ENDPOINT=$(PRODUCTION_API_URL) || set VUE_APP_API_ENDPOINT=$(PRODUCTION_API_URL) && npm run build
  displayName: 'npm install and build'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://$(FTP_URL)'
    username: '$(FTP_USERNAME)'
    password: '$(FTP_PASSWORD)'
    rootDirectory: 'dist'
    filePatterns: '**'
    remoteDirectory: '/$(PRODUCTION_FTP_DIRECTORY)/'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false
=======
    npm run build
  displayName: 'npm install and build'
>>>>>>> 8cb942a0e18424c856b6673bef1aad243163e33f
